# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT paul.wsgi

beta_settings:
    cloud_sql_instances: paulinorochaesilva:us-central1:pauldb

runtime_config:
  python_version: 3
# [END runtime]